# Generated by Django 3.2.16 on 2022-12-18 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=20)),
                ('student_phone', models.CharField(max_length=10)),
                ('student_email', models.CharField(max_length=100)),
                ('student_address', models.CharField(max_length=100)),
                ('student_place', models.CharField(max_length=100)),
            ],
        ),
    ]
